### ISSUE TITLE
Подключение к случайной DHT точке

### ISSUE THREAD

**Issue by nurupo** [kangreon/Tox-Pascal-GUI#2]
> Подключение к сети DHT при помощи случайного сервера из за ранее составленного списка.
> http://kdcodes.blogspot.com/2013/09/tox-gui-objectpascaldelphi.html
## 

> Item := FSettings.ServerList.RandomItem;
> https://github.com/kangreon/Tox-Pascal-GUI/blob/072a391898a378dba91522629a33e539f2477a99/src/toxcore.pas#L643
## 

Вообще-то нужно подключаться ко всем DHT нодам. Клиенты A, B, C, D могут быть подключены только друг к другу и никому больше и клиенты E, F, G, H могут быть подключены только друг к другу и никому больше. (Кстати, все клиенты являются полноценными DHT нодами.) Если подключиться только к первой группе, то вы не будете видеть людей из второй.

**Comment by kangreon** [comment]
Спасибо за подсказку. Сейчас буду исправлять. Почему-то я думал, что сервера синхронизируются между собой и то обстоятельство, что клиенты подключены к разным серверам, лишь увеличит время их (клиентов) первое подключения друг к другу.

**Comment by nurupo** [comment]
По-хорошему, DHT ноды должны подключаться к остальным DHT нодам, но никто этого не требует и нет способа как-либо обязать это соблюдать. В вышеуказанном примере, если любой клиент из одной группы добавит любого другого клиента как DHT ноду, то две сети объединятся. Например, если D присоединится к H, то A, B, C, D и E, F, G, H будут знать о существовании друг друга, даже если D и H уйдут в оффлайн. Так что чем больше сеть, чем больше связей между сетями, тем меньше изолированных сетей.
