### ISSUE TITLE
Странный комментарий

### ISSUE THREAD

**Issue by nurupo** [kangreon/Tox-Pascal-GUI#3]
> //Вы уверене, что лизвеб дает мастер-ns клиентам? '#13#10#13#10'В какой услуге?

[MessageDraw.pas#L334](https://github.com/kangreon/Tox-Pascal-GUI/blob/7b4578f85c59266c562796fee018f7d262d8c296/gui/MessageWidget/MessageDraw.pas#L334)

Так и должно быть?

**Comment by kangreon** [comment]
Исправил. Осталось после отладки кода.

**Comment by nurupo** [comment]
Отлаживать код комментариями из хабра :)

**Comment by kangreon** [comment]
Так уж получилось, что первым сайтом с комментариями, который пришел в голову, оказался именно он. 
[MessageList.pas#L84](https://github.com/kangreon/Tox-Pascal-GUI/blob/6bfd8de15fabe2fabbe6bc71edaa696e46932c2d/src/MessageList.pas#L84)
Работа с базой данных еще не была реализована. Пришлось использовать временный костыль в виде заполнения списка сообщений прямо во время создания класса. Этого вполне хватило для разработки виджета сообщений.
